### PR TITLE
Mastery exercise

### PR DESCRIPTION
**Pull request by J-Waddell**

### CODE REVIEW

**Comment by dmserrano** [comment]
Your code looks good so far but it seems like you are missing a few requirements:

Once the user enters in a number, and a character, the user can either then just press the enter key (as long as the cursor is in one of the input fields), or click a button that is labeled "Grow your tree" and the tree should be shown in the console. This requires you to add an event listener to the button, as well as an event listener for the enter/return key.

If either of the input fields does not have a value in it when the user presses the enter key, or presses the button, then display an alert stating that both fields must have a value.

Let me know if I can help!

**Comment by dmserrano** [comment]
Your revisions look great, both fields are working now. Make sure to remove unneeded console logs after you complete and exercise to declutter the console. Also, your commit history is great, that will be a big help in the future.

I see you already merged the branch, but make sure next time we give a final thumbs up before the merge. Great job, here is the thumbs up anyways! 👍

**Comment by J-Waddell** [comment]
Dude my bad on merging the branches, I accidentally merged them in my terminal. I'm glad i didn't have anything left to fix haha and also thank you for the compliments on my commits! @DominicSerranoC14

**Comment by dmserrano** [comment]
No problem, just a heads up for next time. Yep, keep up the good work! 💯

**Pull request merged**
